import { useState, useEffect } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import { ToastContainer } from 'react-toastify';
import Zoom from 'react-reveal/Zoom';
import Fade from 'react-reveal/Fade';
import 'react-toastify/dist/ReactToastify.css';



import { loadFull } from "tsparticles";
import ParticlesComponent from '../components/ParticleArea/Particles';
import ButtonUp from '../components/ButtonUp';
import Footer from '../components/Footer';

export default function Home() {


  const [botonarriba, setBotonarriba] = useState(false);
  const [ showNotification, setShowNotificacion ] = useState(false)

  useEffect(()=>{
    window.addEventListener('scroll',scrollUp);

    return () => {
      window.removeEventListener('scroll',scrollUp);
    }
  },[])

  const scrollUp = () =>{
    if(window.pageYOffset > 450){
      setBotonarriba(true);
    }else{
      setBotonarriba(false);
    }
  }

  const topPage = () => {
      window.scrollTo({
        top:0,
    })
  }

  const particlesInit = async (main) => {

    await loadFull(main);
  };
  const particlesLoaded = (container) => {

  };

  return (
    <div>
      <Head>
        <title>Manuel Cruz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/react.ico" />
      </Head>
      <Navbar/>
      <ToastContainer autoClose={3000} className="z-10 mt-20 absolute" position='top-right' hideProgressBar={false} pauseOnHover />
      <ParticlesComponent particlesInit={particlesInit} particlesLoaded={particlesLoaded}/>
      <Main/>
      <Fade top>
        <About/>
      </Fade>
      <Fade bottom>
        <Skills/>
      </Fade>
      <Fade top>
        <Projects/>
      </Fade>
      <Zoom bottom>
        <Contact/>
      </Zoom>
      <Footer/>

      <ButtonUp
        botonarriba={botonarriba}
        topPage={topPage}
      />
    </div>
  )
}
