import { useState, useEffect } from 'react';
import Head from 'next/head';
import Navbar from '../components/Navbar';
import Main from '../components/Main';
import About from '../components/About';
import Skills from '../components/Skills';
import Projects from '../components/Projects';
import Contact from '../components/Contact';
import { AiFillCaretUp } from "react-icons/ai";
import Zoom from 'react-reveal/Zoom';
import Fade from 'react-reveal/Fade';


import { loadFull } from "tsparticles";
import ParticlesComponent from '../components/ParticleArea/Particles';

export default function Home() {


  const [botonarriba, setBotonarriba] = useState(false);

  useEffect(()=>{
    window.addEventListener('scroll',scrollUp);

    return () => {
      window.removeEventListener('scroll',scrollUp);
    }
  },[])

  const scrollUp = () =>{
    if(window.pageYOffset > 450){
      setBotonarriba(true);
    }else{
      setBotonarriba(false);
    }
  }

  const topPage = () => {
    window.scrollTo({
      top:0,
  })
  }

  const particlesInit = async (main) => {

    await loadFull(main);
  };
  const particlesLoaded = (container) => {

  };

  return (
    <div>
      <Head>
        <title>Manuel Cruz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/react.ico" />
      </Head>
      <Navbar/>
      <ParticlesComponent particlesInit={particlesInit} particlesLoaded={particlesLoaded}/>
      <Main/>
      <Fade top>
        <About/>
      </Fade>
      <Fade bottom>
        <Skills/>
      </Fade>
      <Fade top>
        <Projects/>
      </Fade>
      <Zoom bottom>
        <Contact/>
      </Zoom>

      {botonarriba === true &&
        <button className='fixed border-2  hover:-translate-y-3 duration-100 bg-[#131212] rounded-md bottom-12 right-12' style={{
          fontSize: "50px"
          }}
          onClick={topPage}>
          <AiFillCaretUp />
        </button>
      }
    </div>
  )
}
